<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5274R1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5274R1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5274R1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5274R1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA5274R1\App_KernelDevDebugContainer([
    'container.build_hash' => 'A5274R1',
    'container.build_id' => 'adc67e4e',
    'container.build_time' => 1710834563,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5274R1');
