<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6Iw0tQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6Iw0tQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC6Iw0tQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC6Iw0tQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC6Iw0tQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'C6Iw0tQ',
    'container.build_id' => '135a29e1',
    'container.build_time' => 1710769127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6Iw0tQ');
