<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjxV1U0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjxV1U0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZjxV1U0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZjxV1U0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZjxV1U0\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZjxV1U0',
    'container.build_id' => 'f31e28fe',
    'container.build_time' => 1710756319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjxV1U0');
